<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DCRI-PF1E2C1F" failures="0" tests="1" name="Colectv_Login.Login_Page" time="18.985" errors="1" timestamp="30 Aug 2023 21:11:58 GMT" skipped="0">
  <testcase classname="Colectv_Login.Login_Page" name="Colectiv_MFA_Login" time="18.985">
    <error message="Authenticate" type="com.twilio.exception.ApiException">
      <![CDATA[com.twilio.exception.ApiException: Authenticate
at com.twilio.rest.api.v2010.account.MessageReader.pageForRequest(MessageReader.java:112)
at com.twilio.rest.api.v2010.account.MessageReader.firstPage(MessageReader.java:99)
at com.twilio.rest.api.v2010.account.MessageReader.read(MessageReader.java:84)
at com.twilio.base.Reader.read(Reader.java:24)
at Colectv_Login.Login_Page.getMessages(Login_Page.java:106)
at Colectv_Login.Login_Page.getMessage(Login_Page.java:98)
at Colectv_Login.Login_Page.Colectiv_MFA_Login(Login_Page.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Colectiv_MFA_Login -->
</testsuite> <!-- Colectv_Login.Login_Page -->
